### ISSUE TITLE
Lab Report 2 Feedback 

### ISSUE THREAD

**Issue by mrkylesmith** [Jameszzyyyyy/cse15l-lab-reports#2]
**Bug/Input 1**
- [x] Commit screenshot for bug/input 1
- [x] Link to test file for bug/input 1
- [x] Symptom shown as command + output for bug/input 1
- [] Description of relationship between bug, symptom, and input for bug/input 1
- When you say, "we should consider very extreme cases about index", please describe what cases you mean and how you deal with that in your code (describe the code change screenshot a little bit).

**Bug/Input 2**
- [x] Commit screenshot for bug/input 2
- [x] Link to test file for bug/input 2
- [x] Symptom shown as command + output for bug/input 2
- [] Description of relationship between bug, symptom, and input for bug/input 2
- Explain how you are removing it from the result.

**Bug/Input 3**
- [x] Commit screenshot for bug/input 3
- [x] Link to test file for bug/input 3
- [x] Symptom shown as command + output for bug/input 3
- [x] Description of relationship between bug, symptom, and input for bug/input 3

Additional comments from your grader:
Good job overall!  Please just add a little bit more detailed description about when you would encounter these symptoms, given a particular bug and how you dealt with them in your code (describe the code changes a little bit).  

Feel free to comment below if you have any questions about the rubric/feedback.

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by Jameszzyyyyy** [comment]
Hello! I have fixed the issues, but I can't send the request for regrade on gradescope.

**Comment by mrkylesmith** [comment]
Well done, I see you added these more detailed descriptions of the relationship between the bug, symptom and input.  I have updated your score to full credit, good job!
